### ISSUE TITLE
[Build] Could not read config.xml from Git, weird behaviour

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#151]
The following 'www' structure couldn't be read properly by Build. It simply ignore config.xml and build totally different app:

https://github.com/amirudin/bluenodSimple
Output: https://build.phonegap.com/apps/440313

Related topic: http://gsfn.us/t/4300b

**Comment by fanfavorite** [comment]
Although deleting the demos of this particular project, the issue still exists. I have the same HTML file names in different directories for various languages. For example, I have:

fr/index.html (French)
index.html (English - Root)

The root directory ends up being fr instead of the actual root www folder. Removing all the additional index.html file makes it work.
