### ISSUE TITLE
Project size limit should be much bigger

### ISSUE THREAD

**Issue by breville** [phonegap/build#194]
The 15 MB limit for a project is way too small for a multimedia app.  Please consider raising this limit into the hundreds of megabytes.

**Comment by goya** [comment]
app sizes have been updated - http://phonegap.com/blog/2014/12/09/phonegap-build-new-features

50MB / 100MB / 1GB

**Comment by hugolpz** [comment]
Thanks ! :)

**Comment by red2678** [comment]
:+1:

**Comment by salbahra** [comment]
I noticed PhoneGap build now supports 50MB size however my repo when cloned is 25MB and I am still getting the 50MB limit error. Is there anything I can do about this?

My app ID is 793070. For the record, my app compiles to 1.3MB on iOS, 800KB on Android, and 650KB on Windows Phone. So I really shouldn't be hitting this limit.

Thank you.

**Comment by goya** [comment]
i notice you were able to upload your source fine?  did you resolve your issue?

**Comment by emberpenumbra** [comment]
HI
 I'm very happy that the upload increase has been made but I don't work at
Phonegap, nor did I upload anything. Could you please take me off this
thread.

Alexis Williams
www.AlexisWilliams.net

**Comment by goya** [comment]
sorry that last comment was for salbahra: if you are still having issues please start an issue at community.phonegap.com

**Comment by salbahra** [comment]
No, the reason there is a successful build is I recently renamed my Github repository and when I updated the project URL in PhoneGap Build, it then started showing the error.

Since this could be an issue with relocating, I tried to start a new app using the Github repository and again the same error message, "App to large".

Currently, I added a Grunt task to zip my www and res dirs with the config.xml and upload using my auth_token to PGB, and that works well with App ID: 1371093. So it tells me my app size is fine but it's related to using Github as a source. I did try to trim my repo down by removing very old unused objects which only removed 3MB however that didn't seem to help. Also, the files in my repo are only 4.9MB however the repo when cloned is 23MB (entire difference is the contents of .git folder). I think this is the source of the error and wondering if we can reduce the size by doing a slightly different clone (--depth 1) or grabbing the zip from Github.

Thank you!

**Comment by goya** [comment]
please start an issue at community.phonegap.com so we can troubleshoot

**Comment by salbahra** [comment]
I did: http://community.phonegap.com/nitobi/topics/unable-to-create-app-app-is-too-large-app-must-be-less-than-50-mb?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=reply_button&reply%5Bid%5D=15502713#reply_15502713
