### ISSUE TITLE
Geolocation Prompt on iOS when Exporting from Construct 2 (Reopening of #440)

### ISSUE THREAD

**Issue by donkeyspaceman** [phonegap/build#442]
[This issue](https://github.com/phonegap/build/issues/440) was closed last week, but still requires attention.

>After building a Construct 2 app with PhoneGap Build, the app will prompt the user with the following message on first run:

>"Allow to access your location even when you are not using the app?"

>This message will appear despite no geolocation features being active in the Construct 2 project.

>This was first reported 5 months ago, where it was believed to be a Construct 2 bug: http://community.phonegap.com/nitobi/topics/how-to-i-turn-off-geolocation-when-using-phonegap-build

>I recently reported it to the Construct 2 developer, who believes it is a PhoneGap bug: https://www.scirra.com/forum/touch-object-creates-location-services-prompt-on-ios_t131269

>My app update was rejected from the app store because of this prompt. A rapid fix would be appreciated.

The following message was added after the ticket was closed:

>@goya - I am the Construct 2 developer. Why does listening for "devicemotion" and "deviceorientation" prompt a location services request? They don't give the location, only the motion and orientation of the device. Also previous versions of Cordova did not show any prompt, and the PhoneGap CLI does not show any prompt, so it seems to be a problem unique to PhoneGap Build.

**Comment by donkeyspaceman** [comment]
Pinging @AshleyScirra

**Comment by wildabeast** [comment]
Doing some more investigating here.

**Comment by ongakugene** [comment]
Same issue is happening in our project also. User is being asked for permission to access location whereas we do not even have any geolocation plugin in the project. Only happening with Phonegap Build. Apple is complaining that we do not use user's location in the app and hence should not ask the user about permission.

**Comment by wildabeast** [comment]
Appear to have found a solution (or workaround) for this issue. Try adding this to your PGB config.xml:

    <gap:config-file platform="ios" parent="NSLocationWhenInUseUsageDescription" mode="replace"> 
        <string>ANYTHING</string> 
    </gap:config-file>

Shouldn't matter what you throw in for the string (unless you are using location stuff elsewhere) since the prompt shouldn't appear. Let us know if it does / doesn't work for you.

Still not sure why this is happening but will update if / when we figure that out.

**Comment by donkeyspaceman** [comment]
That seems to have worked. Thank you SO much for this workaround. I'm very happy to finally get my update accepted on the app store.

**Comment by ongakugene** [comment]
Worked like a charm here as well. Thank you so much!

**Comment by AshleyScirra** [comment]
@wildabeast - that is a workaround, not a fix! PGB should not by default create unnecessary location prompts! The bug is still there and you do not appear to really understand why it happens. Please reopen the issue, find the root cause and resolve it.

Even the workaround presents problems for frameworks like Construct 2: should we just unconditionally drop that line in absolutely everything that is exported? Your example looks like it sets a user-facing description string, in which case it should not be "ANYTHING". What are we supposed to do about this?
