### ISSUE TITLE
[iOS9] Apps become scalable.

### ISSUE THREAD

**Issue by amirudin** [phonegap/build#457]
Received report that app become scalable after upgrading to iOS9

Original topic: http://gsfn.us/t/4sc92

**Comment by wildabeast** [comment]
responded to GS thread.

**Comment by AmsterdamInc** [comment]
I can now confirm that setting the auto-hide-splashscreen setting to false does not help. Also, setting EnableViewportScale to false does not work either.

We do not use any third-party plugins and use Phonegap build 3.7.0 to compile.

New build displays perfectly on iOS 8, updated phone with iOS 9 displays "zoomed in" application.

**Comment by dsternj** [comment]
as recommended updated all plugins to latest npm version and version to cli 5.2.0. No changes at all

**Comment by AmsterdamInc** [comment]
Our app was updated to all latest phonegap and plugin versions, issue still persist.

I can confirm that this issue was caused by one of the iOS splash screen png files missing for the 667h and 736h dimensions. Apparently in iOS 9 this is now a hard requirement, compared to iOS 8, or handled differently by Phonegap. Strange impact for the same app on the same phone and screen.

**Comment by wildabeast** [comment]
As mentioned above, make sure you're including all the [required splash screen sizes](http://docs.build.phonegap.com/en_US/configuring_icons_and_splash.md.html#Icons%20and%20Splash%20Screens).
