### ISSUE TITLE
Way to modify a key

### ISSUE THREAD

**Issue by Heshyo** [phonegap/build#483]
Each time I have to update an iOS certificate or provisioning profile, I have to first delete the current key in PGB then recreate a new one. The problem is that I also have to update any script that makes use of that PGB key. It would help if I could just update the key (ie keep its ID) so that no script would be impacted.

**Comment by goya** [comment]
1. you can specify the signing key with the 'signing-key' preference by title or id: http://docs.phonegap.com/phonegap-build/configuring/preferences/#signing-key
2. you can also set the key as a default and all new apps without a set key will use that key

due to the security around our signing key encryption we cannot allow updating of existing keys.
